language: objective-c
sudo: false
xcode_project: FoundationExtension.xcodeproj
osx_image: xcode7
matrix:
  include:
    - osx_image: xcode7
      xcode_sdk: macosx
      xcode_scheme: CocoaExtension
    - osx_image: xcode7
      xcode_sdk: iphonesimulator
      xcode_scheme: UIKitExtension
    - osx_image: xcode7.3
      xcode_sdk: appletvsimulator
      xcode_scheme: UIKitExtension
    - osx_image: xcode6  # legacy support
      xcode_sdk: macosx10.9
      xcode_scheme: CocoaExtension
  allow_failures:
    - xcode_sdk: appletvsimulator
