language: objective-c
xcode_project: FoundationExtension.xcodeproj # path to your xcodeproj folder
xcode_scheme: FoundationExtension
script: xcodebuild -project FoundationExtension.xcodeproj -target FoundationExtensionTests ONLY_ACTIVE_ARCH=N