language: objective-c
xcode_project: FoundationExtension.xcodeproj # path to your xcodeproj folder
xcode_scheme: CocoaExtensionTests
script: xcodebuild test -project FoundationExtension.xcodeproj -scheme UIKitExtensionTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
